name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deno
        uses: denolib/setup-deno@master
      - run: deno lint --unstable --ignore=dist
      - run: deno fmt --check --ignore=dist